import yaml
from openai import OpenAI
from pathlib import Path

_clients = {}

def load_config(config_path: str) -> dict:
    
    '''
    Description:
        Load configuration from a YAML file.
    Args:
        config_path (str): Path to the YAML configuration file.
    Returns:
        dict: Configuration dictionary loaded from the file.
    Raises:
        FileNotFoundError: If the configuration file does not exist at the specified path.
    '''
    
    if not Path(config_path).is_file():
        raise FileNotFoundError(f"Config file not found at {config_path}")
    with open(config_path) as f:
        config = yaml.safe_load(f)
    return config


def _get_client(config: dict, 
                model_key: str
    ) -> tuple[OpenAI, dict]:
    
    '''
    Description:
        Get an OpenAI client instance for the specified model key, along with its configuration.
    Args:
        config (dict): The configuration dictionary containing model details.
        model_key (str): The key identifying the model in the configuration.
    Returns:
        tuple[OpenAI, dict]: A tuple containing the OpenAI client instance and the model's configuration.
    Raises:
        KeyError: If the model_key is not found in the configuration.
    '''
    
    if "models" not in config or model_key not in config["models"]:
        raise KeyError(f"Model key '{model_key}' not found in configuration.")
    
    cfg = config["models"][model_key]
    if model_key not in _clients:
        _clients[model_key] = OpenAI(
                                    base_url=cfg["base_url"],
                                    api_key="not-needed",
                                )
    return _clients[model_key], cfg

def call_llm(config: str, 
             prompt: str,
            model: str = "qwen", 
            system: str = None, 
            temperature: float = None, 
            max_tokens: int = None
    ) -> str:
    
    '''
    Description:
        Call the specified language model with the given prompt and parameters.
    Args:
        config (dict): The configuration dictionary containing model details.
        prompt (str): The input prompt to send to the language model.
        model (str, optional): The key identifying the model to use from the configuration. Defaults to "qwen".
        system (str, optional): An optional system message to provide context for the model. Defaults to None.
        temperature (float, optional): The sampling temperature for the response. If None, uses the default from the configuration. Defaults to None.
        max_tokens (int, optional): The maximum number of tokens in the response. If None, uses the default from the configuration. Defaults to None.
    Returns:
        str: The response generated by the language model.
    '''
    
    client, cfg = _get_client(config, model)
    
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})
    
    response = client.chat.completions.create(
                                            model=cfg["model_name"],
                                            messages=messages,
                                            temperature=temperature if temperature is not None else cfg["temperature"],
                                            max_tokens=max_tokens or cfg["max_tokens"],
                                        )
    return response.choices[0].message.content

if __name__ == "__main__":
    
    config_path = Path(__file__).parent.parent / "configs" / "config.yaml"
    config = load_config(config_path)
    
    # Quick test
    print("Testing Qwen...")
    # result = call_llm("Write a pandas one-liner to count null values per column")
    result = call_llm(config, "You know about ramayan, what do you think about it?")
    print(f"Response: {result}")
    
    print("Testing Llama...")
    # result = call_llm("Write a pandas one-liner to count null values per column")
    result = call_llm(config, "You know about ramayan, what do you think about it?", 'llama')
    print(f"Response: {result}")